name: CI

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+

env:
  IMAGE_NAME: ${{ secrets.DOCKER_LOGIN }}/tcommerce-web-admin

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log into Docker registry
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_DOCKER_USERNAME }} --password-stdin

    - name: Pull images
      run: |
        docker pull ghcr.io/$GITHUB_REPOSITORY:builder || true
        docker pull ghcr.io/$GITHUB_REPOSITORY:latest || true

    - name: Build images (multistage)
      run: |
        docker build \
          --target builder \
          --cache-from ghcr.io/$GITHUB_REPOSITORY:builder \
          -t ghcr.io/$GITHUB_REPOSITORY:builder \
          .
        docker build \
          --cache-from ghcr.io/$GITHUB_REPOSITORY:latest \
          --cache-from ghcr.io/$GITHUB_REPOSITORY:builder \
          -t ${IMAGE_NAME}:latest \
          .

    - name: Push images
      run: |
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${VERSION} ghcr.io/$GITHUB_REPOSITORY:latest

        docker push ghcr.io/$GITHUB_REPOSITORY:builder
        docker push ghcr.io/$GITHUB_REPOSITORY:latest
        docker push ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}:${VERSION}

  deploy:
    needs: build-push

    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          passphrase: ${{ secrets.SERVER_SSH_PRIVATE_KEY_PASSPHRASE }}
          script: |
            manage-docker pull-restart admin prod
